[mgr]
ratio = [1, 3, 4]
show_hidden = true

[plugin]
append_previewers = [
  { name = "*", run = "hexyl", mime = "application/octet-stream" },
]

[[plugin.prepend_fetchers]]
id = "git"
group = "git"
run = "git"
url = "*"

[[plugin.prepend_fetchers]]
id = "git"
group = "git"
run = "git"
url = "*"
